name: Docker Hub CI

on:
  push:
    branches: [ main ]

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Git repo
    - uses: actions/checkout@v2
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: globart/github_cv
        tags: latest, ${{ github.run_number }}
